development: &dev
  adapter: postgresql
  encoding: unicode
  database: karta_development
  pool: 5
  username: postgres
  password:
  #host: localhost
test: &test
  <<: *dev
  database: karta_test

production:
  <<: *dev
  database: karta_production

cucumber:
  <<: *test